# Generated by Django 5.2.7 on 2025-10-24 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.IntegerField()),
                ('y', models.IntegerField()),
                ('terrain_type', models.CharField(choices=[('WATER', 'Water'), ('LAND', 'Land')], default='WATER', max_length=20)),
            ],
        ),
    ]
