# Generated by Django 5.2.7 on 2025-10-27 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.IntegerField()),
                ('y', models.IntegerField()),
                ('vehicle_type', models.CharField(choices=[('TANK', 'Water'), ('SHIP', 'Ship'), ('PLANE', 'Plane')], default='TANK', max_length=20)),
            ],
        ),
    ]
