# Generated by Django 5.2.7 on 2025-10-27 20:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_level_tile_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tile',
            name='level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tiles', to='game.level'),
        ),
    ]
