# Generated by Django 5.2.7 on 2025-10-30 02:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_alter_tile_level'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='x',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='y',
        ),
        migrations.AddField(
            model_name='vehicle',
            name='level',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to='game.level'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='tile',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to='game.tile'),
        ),
    ]
