# Generated by Django 5.2.7 on 2025-10-31 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_remove_vehicle_x_remove_vehicle_y_vehicle_level_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='vehicle_type',
            field=models.CharField(choices=[('TANK', 'Water'), ('BOAT', 'Boat'), ('PLANE', 'Plane')], default='TANK', max_length=20),
        ),
    ]
