# Generated by Django 5.2.7 on 2025-10-31 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0006_alter_vehicle_vehicle_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='vehicle_type',
            field=models.CharField(choices=[('TANK', 'Water'), ('BOAT', 'Boat'), ('PLANE', 'Plane'), ('ENEMY_TANK', 'Enemy Tank'), ('ENEMY_BOAT', 'Enemy Boat'), ('ENEMY_PLANE', 'Enemy Plane')], default='TANK', max_length=20),
        ),
    ]
