# Generated by Django 5.2.7 on 2025-11-05 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0007_alter_vehicle_vehicle_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tile',
            name='terrain_type',
            field=models.CharField(choices=[('WATER', 'Water'), ('LAND', 'Land'), ('DOCK', 'Dock')], default='WATER', max_length=20),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='vehicle_type',
            field=models.CharField(choices=[('TANK', 'Tank'), ('BOAT', 'Boat'), ('PLANE', 'Plane'), ('ENEMY_TANK', 'Enemy Tank'), ('ENEMY_BOAT', 'Enemy Boat'), ('ENEMY_PLANE', 'Enemy Plane')], default='TANK', max_length=20),
        ),
    ]
