# Generated by Django 5.2.7 on 2025-11-05 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0008_alter_tile_terrain_type_alter_vehicle_vehicle_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='level',
            name='game_started',
            field=models.BooleanField(default=False),
        ),
    ]
