# Generated by Django 5.2.7 on 2025-11-08 03:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0011_vehicle_is_enemy_playerlevelstate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='level',
            name='game_started',
        ),
        migrations.AddField(
            model_name='playerlevelstate',
            name='turn_number',
            field=models.IntegerField(default=1),
        ),
        migrations.CreateModel(
            name='PlayerVehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_type', models.CharField(choices=[('TANK', 'Tank'), ('BOAT', 'Boat'), ('PLANE', 'Plane'), ('ENEMY_TANK', 'Enemy Tank'), ('ENEMY_BOAT', 'Enemy Boat'), ('ENEMY_PLANE', 'Enemy Plane')], max_length=20)),
                ('is_enemy', models.BooleanField(default=False)),
                ('health', models.IntegerField(default=100)),
                ('player_state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to='game.playerlevelstate')),
                ('tile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_vehicles', to='game.tile')),
            ],
        ),
        migrations.CreateModel(
            name='StartingVehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_type', models.CharField(choices=[('TANK', 'Tank'), ('BOAT', 'Boat'), ('PLANE', 'Plane'), ('ENEMY_TANK', 'Enemy Tank'), ('ENEMY_BOAT', 'Enemy Boat'), ('ENEMY_PLANE', 'Enemy Plane')], default='TANK', max_length=20)),
                ('is_enemy', models.BooleanField(default=False)),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to='game.level')),
                ('tile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to='game.tile')),
            ],
        ),
        migrations.DeleteModel(
            name='Vehicle',
        ),
    ]
