# Generated by Django 5.2.7 on 2026-07-06 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0012_remove_level_game_started_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerlevelstate',
            name='current_phase',
            field=models.CharField(choices=[('PLAYER', 'Player'), ('ENEMY', 'Enemy')], default='PLAYER', max_length=10),
        ),
        migrations.AddField(
            model_name='playerlevelstate',
            name='status',
            field=models.CharField(choices=[('IN_PROGRESS', 'In Progress'), ('WON', 'Won'), ('LOST', 'Lost')], default='IN_PROGRESS', max_length=20),
        ),
        migrations.AddField(
            model_name='playervehicle',
            name='has_acted',
            field=models.BooleanField(default=False),
        ),
    ]
